### ISSUE TITLE
Outdated mixpanel plugin

### ISSUE THREAD

**Issue by alvarotech** [samzilverberg/cordova-mixpanel-plugin-testapp#2]
Why not updating mixpanel plugin to last version? Doing ionic state restore loads com.samz.mixpanel plugin, which doesn't have majority of the functions supported now by cordova-mixpanel-plugin. It would allow everyone to extend test app to identify people, send push notifications, and many more

**Comment by samzilverberg** [comment]
no reason, just didnt have time to look at this project in the last couple of months.

its just a matter of using the new npm style plugin id right?
com.samz.mixpanel -> cordova-mixpanel-plugin

**Comment by samzilverberg** [comment]
merged the related pr
